name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]

    name: P${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

      - name: Install dependencies for PHP 8.1
        if: matrix.php == '8.1'
        run: composer require pestphp/pest:^2.0 --no-interaction --no-update && composer install -n --prefer-dist

      - name: Install dependencies for PHP 8.2
        if: matrix.php == '8.2'
        run: composer install -n --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
